const concerts = [
	{
		id: 1,
		artist: "GREEN DAY",
		img: "../IMG/grd1.jpg",
		date: "15 Februari 2025",
		location: "Carnaval Ancol, Jakarta",
		description: "THE WAIT IS OVER!One of the world's greatest bands, Green Day is coming to Indonesia!Don't miss their legendary performance on February 15, 2025, at Carnaval Ancol, Jakarta. prepare yourself for a night of high energy, nostalgia, and unforgettable memories with Green Day!",
		mapLink: "https://goo.gl/maps/example1",
		tickets: [
			{ class: "VIP", price: "Rp 2.665.000", available: 20 },
			{ class: "Reguler", price: "Rp 1.580.000", available: 50 },
			{ class: "Festival", price: "Rp 2.050.000", available: 100 },
		],
	},
	{
		id: 2,
		artist: "UBS Gold FEST 2024",
		img: "../IMG/g2.jpg",
		date: "14 Desember 2024",
		location: "Lap. Tenis Senayan, Jakarta",
		description: "Live Performace & UBS gold Brand ambasador meet up.",
		mapLink: "https://goo.gl/maps/example2",
		tickets: [
			{ class: "VIP", price: "Rp 800.000", available: 10 },
			{ class: "Reguler", price: "Rp 400.000", available: 40 },
		],
	},
	{
		id: 3,
		artist: "SHADES & LIFE FESTIVAL",
		img: "../IMG/g3.jpg",
		date: "14 Desember 2024",
		location: "14.00 - 22.00 - Pangudi Luhur, Jakarta",
		description: "Beragam acara dan Penampilan dari band-band rock indonesia yang spektakuler dan menghibur.",
		mapLink: "https://goo.gl/maps/example3",
		tickets: [
			{ class: "VIP", price: "Rp 1.200.000", available: 15 },
			{ class: "Reguler", price: "Rp 600.000", available: 60 },
		],
	},
	{
		id: 4,
		artist: "LINKINPARK FROM WORLD ZERO TOUR",
		img: "../IMG/lkp1.jpeg",
		date: "16 Februari 2025",
		location: "Stadium Madya, Gelora Bung Karno",
		description:
			`Live Nation, TEM Presents,and PK Entertainmentare thrilled to bring LINKIN PARK back to Jakarta for their highly anticipated "FROM ZERO WORLD TOUR". Mark your calendars for this epic show on 16 February 2025 at Stadion Madya Gelora Bung Karno. As part of the global tour celebrating their new album FROM ZERO, LINKIN PARK promises an unforgettable night of music and energy that fans have been eagerly awaiting. The SE Asia leg of the "FROM ZERO WORLD TOUR" will only be performed in Jakarta.`,
		mapLink: "https://goo.gl/maps/example4",
		tickets: [
			{ class: "VIP", price: "Rp 4.500.000", available: 20 },
			{ class: "Reguler", price: "Rp 1.500.000", available: 300 },
			{ class: "Festival", price: "Rp 2.550.000", available: 80 },
		],
	},
	{
		id: 5,
		artist: "30th RUMAHSAKIT",
		img: "../IMG/rm1.jpeg",
		date: "23 November 2024",
		location: "Smi Building, Semarang",
		description: "30th Perjalanan RUMAHSAKIT tour Nasional.",
		mapLink: "https://goo.gl/maps/example5",
		tickets: [
			{ class: "VIP", price: "Rp 289.000", available: 8 },
			{ class: "Presale", price: "Rp 125.000", available: 45 },
		],
	},
	{
		id: 6,
		artist: "ISYANA SARASVATI: LOST IN HARMONY",
		img: "../IMG/isn1.jpg",
		date: "16 November 2025",
		location: "Istoria Senayan",
		description: "Counting down to November 16th!Siap jadi bagian dari sejarah perjalan bermusik Isyana. ISYANA SARASVATI: LOST IN HARMONY, A Decade Live Concert,Tanggal 16 November2024, di Istora Senayan, Jakarta",
		mapLink: "https://goo.gl/maps/example6",
		tickets: [
			{ class: "VIP", price: "Rp 2.499.000", available: 12 },
			{ class: "Reguler", price: "Rp 1.099.000", available: 70 },
			{ class: "Festival", price: "Rp 750.000", available: 150 },
		],
	},
];
